spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_base?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ctj138282
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: admin

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.cloudbase.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8082
  servlet:
    context-path: /api
